# Generated by Django 5.1 on 2024-10-22 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks1', '0002_menu_alter_task_datecompleted_menuselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='menuselection',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_selections', to='tasks1.menu'),
        ),
    ]
