# Generated by Django 5.1 on 2025-01-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks1', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='low_carb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='Sin nombre', max_length=255),
        ),
        migrations.AddField(
            model_name='menu',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
    ]
